---
title: "Shiny App Visualizations"
author: "Hector Corrales"
date: "October 14, 2017"
output: html_document
---
#1) Load Libraries
```{r, message=FALSE, warning=TRUE, include=FALSE}
library(plyr)
library(dplyr)
library(lubridate)
library(chron)
library(tm)
library(ggmap)
library(xts)
library(dygraphs)
library( highcharter)
```

#2) Apprehensions

```{r}

aprehensiones <- read.csv("data/deportados/aprehensiones.csv", stringsAsFactors = FALSE)
#aprehensiones$month <- mdy(aprehensiones$mes)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = aprehensiones$month) %>% 
  hc_add_series(data = aprehensiones$total,
                name = "Total Apprehended") %>%
  hc_add_series(data = aprehensiones$menores,
                name = "Minors Apprehended") %>%
  hc_chart(type = "line") %>% 
  
  hc_title(text = "Monthly Apprehensions at the Southwest Border",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: CBP Biweekly report.", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)
  
  
```

#2) Returned from US and Mexico

```{r Retornados, include=FALSE}
retornados <- read.csv("data/deportados/retornados.csv")

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = retornados$month) %>% 
    hc_add_series(data = retornados$totalretornados,
                name = "Total Returnees", fillOpacity = 0.3) %>%
  hc_add_series(data = retornados$retornadosmex,
                name = "Returnees from Mexico and CA", fillOpacity = 0.5) %>%
  hc_add_series(data = retornados$retornadosus,
                name = "Returnees from US", fillOpacity = 0.7) %>%

  hc_chart(type = "area") %>% 
  
  hc_title(text = "Honduran Returnees",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: Honduras Ministry of Foreign Affairs.", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)
  

```

#3) Electronic Travel Documents Issued

```{r ETD's}


etd <- read.csv("graficos/immigration/etdsmonthly.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = etd$month) %>% 
  hc_add_series(data = etd$count,
                name = "Total ETD's Issed") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "ETD's Issued By Month",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "ICE ETD Platform", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)


  
```

#4) Homicides

```{r Homicides}

homicidios <- read.csv("graficos/security/homicidios.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = homicidios$month) %>% 
  hc_add_series(data = homicidios$homicidios,
                name = "Homicides") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "Number of Homicides per Month",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: Honduran Ministry of Security", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)


  
  
```

#5) Extortion

```{r}

extortion <- read.csv("graficos/security/extortion.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = extortion$year) %>% 
  hc_add_series(data = extortion$complaints,
                name = "Cases received") %>%
  hc_add_series(data = extortion$arrested,
                name = "Arrests made") %>%
  hc_add_series(data = extortion$advisories,
                name = "Consultations given") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "Extortion Statistics",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: National Anti-extortion Force", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)




```


#6) Real GDP Growth

```{r}

gdp <- read.csv("graficos/economy/gdp.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = gdp$year) %>% 
  hc_add_series(data = gdp$gdp,
                name = "GDP Growth") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "Real GDP Growth",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: World Bank/IMF", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             valueSuffix = "%",
             shared = TRUE)
```

#7) Remittances as a percentage of GDP

```{r}

gdprem <- read.csv("graficos/economy/gdprem.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = gdprem$year) %>% 
  hc_add_series(data = gdprem$remgdp * 100,
                name = "Remmitances as % of GDP") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "Remmitances as a percent of GDP",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: Honduran Central Bank", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)

```

#8) Trade Balance

```{r}

trade <- read.csv("graficos/economy/gdprem.csv", stringsAsFactors = FALSE)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = trade$year) %>% 
  hc_add_series(data = round(trade$imports/1000, 1),
                name = "Total Imports") %>%
  hc_add_series(data = round(trade$exports/1000, 1),
                name = "Total Exports") %>%
  hc_add_series(data = round((trade$imports - trade$exports)/1000, 1),
                name = "Trade Deficit", color = "lightgray") %>%
  
  hc_chart(type = "line") %>% 
  
  hc_title(text = "Honduras Trade Balance (in billions of USD)",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: Honduras Central Bank", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE, split = TRUE, 
             valuePrefix = "$", valueSuffix = " billion")
```


#9 FDI as a percentage of GDP

```{r}

fdi <- read.csv("graficos/economy/gdprem.csv", stringsAsFactors = FALSE)

fdi$fdigdp <- round(fdi$fdi/fdi$gdp*100, 1)

highchart() %>% hc_add_theme(hc_theme_smpl())%>%
  
  hc_xAxis(categories = fdi$year) %>% 
  hc_add_series(data = fdi$fdigdp,
                name = "FDI as % of GDP") %>%

  hc_chart(type = "line") %>% 
  
  hc_title(text = "Foreign Direct Investment as a percent of GDP",
           style = list(color = "#2d323a", fontSize = "27px", 
                        fontFamily = "Franklin Gothic Medium Cond", style = "bold")) %>%
  hc_subtitle(text = "Source: Honduran Central Bank", 
              style = list(color = "#525c6b", fontSize = "17px", 
                           fontFamily = "Times New Roman", style = "bold")) %>%
  hc_tooltip(animation = TRUE,
             followPointer = FALSE,
             headerFormat = '<span style="font-size: 14px">{point.key}</span><br/>', 
             shared = TRUE)
```











